# wrangler.toml
name = 'iowaradiooperators'
compatibility_date = "2025-04-04"

[build]
command = "chmod +x build.sh && ./build.sh"

[assets]
directory = "public"
not_found_handling = "404-page"

[vars]
HUGO_VERSION = "0.145.0"
HUGO_ENV = "production"
NODE_VERSION = "22.0.0"
TZ = "America/Chicago"